AllCops:
  Exclude:
    - 'torrentify.gemspec'
    - 'vendor/bundle/**/*'


Style/HashSyntax:
  EnforcedStyle: hash_rockets

Style/ClassVars:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Lint/Eval:
  Enabled: false