language: ruby
rvm:
  - 2.0.0
  - 2.1.0
  - 2.2.0
  - 2.2.1
  - 2.3.0
before_install: gem install bundler -v 1.11.2

env:
  global:
    -  CODECLIMATE_REPO_TOKEN="dde4ba83df1f56ca989e97fa0ce037374f2aca04225a15f0e06f6a597e0749e2"

after_success:
  - bundle exec rake codeclimate
  - bundle exec rake coveralls
